#!/bin/bash

set -e

cp .env.${ENV} .env

if [ "${ENV}" == "local" ]; then
	if [ ! -d "vendor" ]
	then
	    echo "Install dependencies by composer install"
	    composer install
	fi
fi


echo "Clear cache"
php artisan cache:clear


echo "Migrate the database with force"
php artisan migrate --force


echo "Seeding the database"
php artisan db:seed --force


# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi

exec "$@"
